### PR TITLE
search select fields

### LINKED ISSUE #473: Add a search bar to drop downs
Add a search bar to drop downs with many values such as enchantment filter

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #473

### CODE REVIEW

**Comment by Ekwav** [comment]
looks like the classes weren't whitelisted
image

**Comment by Ekwav** [comment]
This still looks not correct.
image


I imagined it like this component: 
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html

**Comment by matthias-luger** [comment]
It works for me.
Did you npm install?

**Comment by Ekwav** [comment]
Yes, I have, doesn't work. How is it supposed to look like?

**Pull request merged**
