### PR TITLE
fix filter styling

### LINKED ISSUE #373: Filter broken
The style appears to be broken
image

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #373

### CODE REVIEW

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-374.flou21.de

**Review by Ekwav — CHANGES_REQUESTED** [review]
its better, but not quite right yet?
image

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-374.flou21.de

**Review by Ekwav — CHANGES_REQUESTED** [review]
same issues 
image

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-374.flou21.de

**Pull request merged**
