### PR TITLE
generic filter grouping

### LINKED ISSUE #343: Group enchant type and level
Group the filters `Enchantment` with `EnchantLvl`
and `SecondEnchantment` with `SecondEnchantLvl`
They can't really be used alone.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #343

### CODE REVIEW

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-357.flou21.de

**Review by Ekwav — CHANGES_REQUESTED** [review]
Removing one filter of a group should remove all of them as 
they can't be used alone

**Review by Ekwav — CHANGES_REQUESTED** [review]
don't use the `getFilter` command, it is deprecated.
Use `filterFor` instead

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-357.flou21.de

**Review by Ekwav — CHANGES_REQUESTED** [review]
The style appears to be broken
image

**Comment by matthias-luger** [comment]
> The style appears to be broken
> image

fixes in #374

**Review by Ekwav — APPROVED** [review]
lgtm

**Pull request merged**
