### PR TITLE
added item tab in player details

### LINKED ISSUE #876: tem data
we are hosting the tem database for more than 4 months

here is a little api i just started:
Screenshot 2022-07-21 at 23 28 07

https://sky.coflnet.com/api/tem/swagger/index.html

UI would be good

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #876

### CODE REVIEW

**Comment by Flou21** [comment]
is this still relevant?

**Comment by matthias-luger** [comment]
@Ekwav The TEM endpoint(s) dont seem to work anymore: 
Example: https://sky.coflnet.com/api/tem/playerProfile/d06eccea-361a-4418-8d7d-69f80b4b6a37

**Comment by Ekwav** [comment]
I think @Flou21 stopped TEM because it wasn't used and expensive. Those endpoint(s) aren't from me

**Comment by matthias-luger** [comment]
As the data doesn't get updated anymore and is therefore basically useless

**Pull request closed without merging**
