### PR TITLE
[WAITING FOR FRONTEND] display nbt data

### LINKED ISSUE #320: Expand NBT-Data
Display the NBT-Data directly under AuctionDetails
also remove one instance of `category` (it is there twice)

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #320

### CODE REVIEW

**Comment by matthias-luger** [comment]
I now take the nbtData-Object and show it in key-value pairs.
If the value is another object, I currently show them in a list (like the enchantments). That may not be ideal for some cases.
I think we should talk about how I get the data again.

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-340.flou21.de

**Comment by Ekwav** [comment]
What are you waiting for? The backend returns the list `flatNbt` as part of auctionDetails

**Comment by Ekwav** [comment]
See here for a list of items with tag: https://github.com/Coflnet/HypixelSkyblock/blob/f54eea592648a4798ad1bd011f36f9f1d8489c6d/Data/NBT.cs#L129

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-340.flou21.de

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-340.flou21.de

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-340.flou21.de

**Review by Ekwav — APPROVED** [review]
YAY NBT is displayed :1st_place_medal:

**Pull request merged**
