### PR TITLE
Removed default React from components

### PR DESCRIPTION
**Pull request by ashishsurya**
Hey,
This is my first open source contribution.

### CODE REVIEW

**Comment by matthias-luger** [comment]
@ashishsurya Thanks for your contribution. I kinda want to wait for #1047 to be merged before merging this though, because I already reviewed that PR and it changes a lot of import statements as well and this might otherwise cause a lot of merge conflicts :)

**Comment by ashishsurya** [comment]
> 

@matthias-luger  Can you inform me after the merging of #1047 is completed?

**Comment by matthias-luger** [comment]
@ashishsurya Sure :)

**Comment by matthias-luger** [comment]
@ashishsurya So yeah the other PR was merged. As I said it touched a lot of files so sadly there are a lot of merge conflicts. Sorry about that.

Also: While glancing over your PR I saw some large changes because of different formatters. To solve that issue I pushed a ".prettierrc" config file into develop that should be used :)

**Pull request closed without merging**
