### PR TITLE
Similar items

### LINKED ISSUE #1062: Display related items
There should be a section on `/item/{uuid}` that displays similar items for quick access.   
Similar/related items can be received from `/api/item/{uuid}/similar`

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #1062

### CODE REVIEW

**Comment by Ekwav** [comment]
Looks good to me.
Maybe the collapsed text could be moved next to an existing element to take up no extra space on large screens.
The test suit fails now as well.
Other than that everything great 👍

**Comment by matthias-luger** [comment]
@Ekwav Pow?

**Comment by matthias-luger** [comment]
@Ekwav ?

**Review by Ekwav — APPROVED** [review]
LGTM 👍

**Pull request merged**
