### PR TITLE
could fix the floating flip on weird browsers

### LINKED ISSUE #417: Floating flip
image

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #417

### CODE REVIEW

**Review by Ekwav — COMMENTED** [review]
Why is the element rendered in the first place?

**Comment by matthias-luger** [comment]
Its rendered to calculate the height of one flip for the customization the user selected

**Comment by Ekwav** [comment]
> Its rendered to calculate the height of one flip for the customization the user selected

But that is only necessary if the value changes.
Not a continuous operation

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by matthias-luger** [comment]
I would suggest to let it stay the way it is.
In the current implementation an error by rendering the list in a wrong height/width is basically out of the question.
If I would hide the demo-flip after checking the height, i have to be careful and react to every change to the settings/styling/structure of the page and the flips.

I would sacrifice minimal performance for a more future proof code.

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/422

**Comment by Ekwav** [comment]
Don't quite get why you would need to take care of every update just only render it why the modification window is open, but what do I know

**Pull request merged**
