### PR TITLE
Fix supported number format

### LINKED ISSUE #1087: Fix supported number format
Number input with `1m-2m` is supported by the backend but not recognized as valid on the frontend.
It should be allowed.
https://cdn.discordapp.com/attachments/872359685741760532/1090994889807896728/Screenshot_20230330-094356.png

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #1087 

This not only fixes the number filter validation, but pretty much any validation which was broken until now.
Also adds hadler for invalid form to make it impossible to for example add a invalid restriction item

waits for #1088

### CODE REVIEW

**Comment by matthias-luger** [comment]
@Ekwav

**Comment by matthias-luger** [comment]
bump again :(

**Comment by matthias-luger** [comment]
@Ekwav :(

**Review by Ekwav — APPROVED** [review]
LGTM! :)

**Pull request merged**
