### PR TITLE
fix window.performance for safari

### LINKED ISSUE #594: issues on safari
It was reported that the homepage could not be loaded on safari

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #594

### CODE REVIEW

**Comment by Flou21** [comment]
error:
IMG_30BB9E48B152-1 2

**Review by Flou21 — CHANGES_REQUESTED** [review]
see screenshot

**Comment by Flou21** [comment]
@matthias-luger should be fixed now, can i merge that?

**Review by neustainspire — APPROVED** [review]

**Comment by matthias-luger** [comment]
@Flou21 if it works you can merge it

**Pull request merged**
