### PR TITLE
shorten copy message and dont pause on lost focus

### LINKED ISSUE #418: shorten the display time of "copied command"
The display time of the "copied command /viewauction ..." is displayed to long (doesn't go away fast enough) it should be displayed for 0,5-1 second.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #418

### CODE REVIEW

**Review by Ekwav — APPROVED** [review]
This was more a one or the other but I will take it

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env.flou.dev/421

**Pull request merged**
