### PR TITLE
dynamically hide flip fields

### LINKED ISSUE #336: Make flip-attributes dynamically show/hide-able
There are a lot of interesting things for every flip. Some users might not be interested in all or interested in others than normally displayed.
Develop a system that allows hiding properties and allow users to change the displayed properties via a settings view/page.
Requirements:
- all fields should be toggable 
- selection should be saved

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #336

only merge with #338

### CODE REVIEW

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-363.flou21.de

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-363.flou21.de

**Comment by Flou21** [comment]
[CI] created a pr environment: https://pr-env-sky-363.flou21.de

**Comment by Ekwav** [comment]
If these two pull requests depend on each other you should merge the into one

**Comment by matthias-luger** [comment]
merged into #368

**Pull request closed without merging**
