### PR TITLE
allow next to run on different basePath

### PR DESCRIPTION
**Pull request by matthias-luger**

### CODE REVIEW

**Comment by matthias-luger** [comment]
@Flou21 could you setup such an environment again and link it here?
I just tried to reproduce the problem with the links locally and everything seems to work. What exactly did you put it as BASE_PATH?

**Comment by Flou21** [comment]
image

**Comment by matthias-luger** [comment]
@Flou21 Just tried it with your value. The links still work perfectly fine... Could you setup such an environment to test it again?
image

**Comment by matthias-luger** [comment]
Thats what I changed:
image
image

**Comment by Flou21** [comment]
@matthias-luger status?

**Comment by matthias-luger** [comment]
@Flou21 This is the same change I did in develop. Somehow it worked there? So I would say we can close this, right?

**Pull request closed without merging**
