### PR TITLE
Next 13 upgrade

### PR DESCRIPTION
**Pull request by matthias-luger**
update to next 13
update basically all other npm packages as well

### CODE REVIEW

**Comment by matthias-luger** [comment]
@Ekwav Never mind the review. While it seems like the production build runs fine (at least it looks like it), the dev build still throws a lot of thing that I still need to fix. 
So the review sadly has to wait for now

**Comment by matthias-luger** [comment]
@Ekwav I think this is ready for you to take a look now if you want :)

**Review by Ekwav — CHANGES_REQUESTED** [review]
The tests should pass

**Comment by matthias-luger** [comment]
@Ekwav Took a few runs but the tests ran through

**Pull request merged**
